=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej3/PostigoJavier_ej3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="sistema_sanitario" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hospitales" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="ubicacion" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="medicos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="dni" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="domicilio" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="pacientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha_nacimiento" type="xs:date" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="informacion_ingresos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha" type="xs:date" />
                                        <xs:element name="fecha_alta" type="xs:date" />
                                        <xs:element name="motivo" type="xs:string" />
                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej3/PostigoJavier_ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<sistema_sanitario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="PostigoJavier_ej3.xsd">
    <hospitales id="3">
    <nombre>Reina Sofia</nombre>
    <ubicacion>Avenida de la arruzafilla</ubicacion>
    </hospitales>

    <medicos id="423">
        <nombre>Jose Miguel</nombre>
        <dni>49505032W</dni>
        <apellido>Torres</apellido>
        <domicilio>Calle Pintor Zurbarán</domicilio>
    </medicos>

    <pacientes id="953">
        <fecha_nacimiento>2003-05-26</fecha_nacimiento>
        <nombre>Javier</nombre>
        <apellido>Postigo Arévalo</apellido>
        <informacion_ingresos>
           <fecha>2022-05-15</fecha>
           <fecha_alta>2022-05-15</fecha_alta>
           <motivo>Apendicitis</motivo>
        </informacion_ingresos>
    </pacientes>

</sistema_sanitario>
