=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej7/PostigoJavier_ej7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inmobiliaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="correo_electronico" type="xs:string" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="telefono" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="propietarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propietario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="propiedades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propiedad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="num_pisos"  >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="150"/>

                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="propietario_perteneciente">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:string" />
                                                    <xs:element name="nombre" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pisos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="piso">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="precio">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="fecha_alta" type="xs:string" />
                                        <xs:element name="calidad">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="A"/>
                                                            <xs:enumeration value="B"/>
                                                            <xs:enumeration value="C"/>
                                                            <xs:enumeration value="D"/>
                                                            <xs:enumeration value="E"/>
                                                            <xs:enumeration value="F"/>

                                                        </xs:restriction>
                                                    </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="propiedad_perteneciente">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:string" />
                                                    <xs:element name="nombre" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required" >
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[fF][0-9]{1,5}"></xs:pattern>

                                            </xs:restriction>
                                        </xs:simpleType>
                                        </xs:attribute>


                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej7/PostigoJavier_ej7.xml
<?xml version="1.0" encoding="UTF-8"?>
<inmobiliaria    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="PostigoJavier_ej7.xsd"> 

<agencias>
    <agencia id="23">
        <correo_electronico>a21poarja@iesgrancapitan.org</correo_electronico>
        <nombre>Agencia Javier</nombre>
        <telefono>624 50 41 49</telefono>
    </agencia>


</agencias>

<propietarios>

    <propietario id="24">
        <nombre>Javier</nombre>

    </propietario>    
</propietarios>

<propiedades>
    <propiedad id="45">
        <nombre>Pisos Javier</nombre>
        <num_pisos>151</num_pisos>
        <propietario_perteneciente>
            <id>24</id>
            <nombre>Javier</nombre>
        </propietario_perteneciente>
    </propiedad>

</propiedades>

<pisos>
    <piso id="F51">
        <nombre>PisoGrande</nombre>
        <descripcion>Piso de 500 metros cuadrados, con piscina.</descripcion>
        <precio>5000000</precio>
        <fecha_alta>2022-05-14</fecha_alta>
        <calidad>A</calidad>
        <propiedad_perteneciente>
            <id>   45 </id>
            <nombre> Casa Javier </nombre>
        </propiedad_perteneciente>

    </piso>

</pisos>
</inmobiliaria>
