=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej5/PostigoJavier_ej5.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="inmobiliaria" type="inmobiliariaType"/>
  <xs:complexType name="agenciaType">
    <xs:sequence>
      <xs:element type="xs:string" name="correo_electronico"/>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:string" name="telefono"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="agenciasType">
    <xs:sequence>
      <xs:element type="agenciaType" name="agencia"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="propietarioType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="propietariosType">
    <xs:sequence>
      <xs:element type="propietarioType" name="propietario"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="propiedadType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:string" name="num_pisos"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="propiedadesType">
    <xs:sequence>
      <xs:element type="propiedadType" name="propiedad"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pisoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:string" name="descripcion"/>
      <xs:element type="xs:string" name="precio"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pisosType">
    <xs:sequence>
      <xs:element type="pisoType" name="piso"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="inmobiliariaType">
    <xs:sequence>
      <xs:element type="agenciasType" name="agencias"/>
      <xs:element type="propietariosType" name="propietarios"/>
      <xs:element type="propiedadesType" name="propiedades"/>
      <xs:element type="pisosType" name="pisos"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== JavierPA3/JavierPA3.github.io/unidad6/PostigoJavier_ej5/PostigoJavier_ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<inmobiliaria  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="PostigoJavier_ej5.xsd">

<agencias>
    <agencia>
        <correo_electronico>a21poarja@iesgrancapitan.org</correo_electronico>
        <nombre>Agencia Javier</nombre>
        <telefono>624 50 41 49</telefono>
    </agencia>


</agencias>

<propietarios>

    <propietario>
        <nombre>Javier</nombre>

    </propietario>    
</propietarios>

<propiedades>
    <propiedad>
        <nombre>Casa Javier</nombre>
        <num_pisos>2</num_pisos>
    </propiedad>

</propiedades>

<pisos>
    <piso>
        <nombre>PisoGrande</nombre>
        <descripcion>Piso de 500 metros cuadrados, con piscina.</descripcion>
        <precio>5000000</precio>

    </piso>

</pisos>
</inmobiliaria>
